### ISSUE TITLE
请问jx_cfd.js一直报错

### ISSUE THREAD

**Issue by Annyoo2021** [moposmall/Script#3]
跑了2-3个号就报错 不跑了：
❗️京喜财富岛, 错误!
TypeError: Cannot read property 'startsWith' of undefined
    at /jd/scripts/jx_cfd.js:928:27
    at /jd/scripts/jx_cfd.js:1572:13
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

❗️京喜财富岛, 错误!
TypeError: Cannot read property 'startsWith' of undefined
    at /jd/scripts/jx_cfd.js:982:19
    at /jd/scripts/jx_cfd.js:1521:13
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

**Comment by moposmall** [comment]
更新一下
