### ISSUE TITLE
清空白菜报错

### ISSUE THREAD

**Issue by 2284787774** [moposmall/Script#4]
❗️京喜牧场清空白菜, 错误!
ReferenceError: resolve is not defined
    at /ql/scripts/moposmall_jd_scripts_jx_mc_emptycabbage.js:60:21
    at processTicksAndRejections (internal/process/task_queues.js:95:5)

**Comment by 2284787774** [comment]
报错后直接结束，不会跑下一个账号

**Comment by 2284787774** [comment]
每次到领取鸡蛋的时候也出错，要重新运行才会领取

**Comment by moposmall** [comment]
更新一下

**Comment by 2284787774** [comment]
> 更新一下

开始【京东账号1】13288464122_p

【获取用户信息📝】：成功

{"data":{"maintaskId":"pause"},"message":"小鸡吃太多影响健康，明天再喂吧","ret":2005}

【投喂🥬】小鸡吃太多影响健康，明天再喂吧，请加大力度～ 
  

【获取用户信息📝】：成功


❗️京喜牧场清空白菜, 错误!
ReferenceError: resolve is not defined
    at /ql/scripts/moposmall_Script_jx_mc_emptycabbage.js:59:21
    at processTicksAndRejections (internal/process/task_queues.js:95:5)

🔔京喜牧场清空白菜, 结束! 🕛 3.918 秒


## 执行结束... 2021-06-29 20:17:46  耗时 5 秒
还是报错直接停止，不会跑下一个账号

**Comment by moposmall** [comment]
> > 更新一下
> 
> 开始【京东账号1】13288464122_p
> 
> 【获取用户信息📝】：成功
> 
> {"data":{"maintaskId":"pause"},"message":"小鸡吃太多影响健康，明天再喂吧","ret":2005}
> 
> 【投喂🥬】小鸡吃太多影响健康，明天再喂吧，请加大力度～
> 
> 【获取用户信息📝】：成功
> 
> ❗️京喜牧场清空白菜, 错误!
> ReferenceError: resolve is not defined
> at /ql/scripts/moposmall_Script_jx_mc_emptycabbage.js:59:21
> at processTicksAndRejections (internal/process/task_queues.js:95:5)
> 
> 🔔京喜牧场清空白菜, 结束! 🕛 3.918 秒
> 
> ## 执行结束... 2021-06-29 20:17:46 耗时 5 秒
> 还是报错直接停止，不会跑下一个账号

你把你的完整日志发一下我看看

**Comment by 2284787774** [comment]
> 更新一下

🔔京喜牧场清空白菜, 开始!
您的cookie选择的是用&隔开


====================共有12个京东账号Cookie=========

==================脚本执行- 北京时间(UTC+8)：2021/6/30下午5:12:07=====================


开始【京东账号1】13288464122_p

【获取用户信息📝】：成功

{"data":{"maintaskId":"pause"},"message":"小鸡吃太多影响健康，明天再喂吧","ret":2005}

【投喂🥬】小鸡吃太多影响健康，明天再喂吧，今天不要再运行此脚本了~ 
  

【获取用户信息📝】：成功


🔔京喜牧场清空白菜, 结束! 🕛 3.567 秒


## 执行结束... 2021-06-30 17:12:10  耗时 3 秒

最新的虽然不报错了可是还是直接结束不会跑下一个账号
